<?php
/**
 * templates/pdf/default-layout.php
 *
 * Variables available:
 * - $products_for_template (array)
 * - $pdf_bg_html (string) HTML div for the full-page background template image
 * - $show_price (yes|no)
 * - $show_attributes (yes|no)
 *
 * قالب پی‌دی‌اف: اگر ادمین یک تصویر قالب (کاور از پیش طراحی‌شده) در تنظیمات آپلود کرده باشد،
 * آن تصویر به‌عنوان پس‌زمینه تمام‌صفحه روی همه صفحات تکرار می‌شود و محتوای محصولات
 * (تصویر اصلی، عنوان، قیمت، ویژگی‌ها) با پس‌زمینه نیمه‌شفاف روی آن قرار می‌گیرد.
 * محتوای کاتالوگ چپ‌چین (LTR) است و از فونت DejaVu Sans به‌عنوان پیش‌فرض استفاده می‌کند.
 */
?>
<!doctype html>
<html lang="fa" dir="ltr">
<head>
    <meta charset="utf-8">
    <style>
        @page { margin: 20mm 16mm; }
        * { box-sizing: border-box; }
        body {
            font-family: "DejaVu Sans", sans-serif;
            direction: ltr;
            text-align: left;
            font-size: 12px;
            color: #222;
            line-height: 1.3;
            margin: 0;
        }

        /* تصویر قالب PDF: پس‌زمینه تمام‌صفحه که روی همه صفحات تکرار می‌شود */
        .wc-pdf-page-bg {
            position: fixed;
            top: -20mm;
            left: -16mm;
            right: -16mm;
            bottom: -20mm;
            width: 210mm;
            height: 297mm;
            background-size: cover;
            background-position: center;
            background-repeat: no-repeat;
            z-index: -1;
        }

        .catalog {
            width: 100%;
        }
        .product {
            display: flex;
            align-items: flex-start;
            margin-bottom: 12px;
            padding: 10px;
            border-bottom: 1px solid #eee;
            background: rgba(255, 255, 255, 0.86);
            border-radius: 4px;
        }
        .product img {
            width: 120px;
            height: auto;
            object-fit: contain;
            margin-right: 12px;
            border: 1px solid #ddd;
            padding: 4px;
            background: #fff;
        }
        .meta {
            flex: 1;
        }
        .title {
            font-weight: bold;
            font-size: 14px;
            margin-bottom: 6px;
        }
        .price {
            color: #0073aa;
            font-weight: bold;
            margin-bottom: 6px;
        }
        .attributes {
            font-size: 11px;
            color: #555;
        }
        .footer-note {
            margin-top: 20px;
            font-size: 11px;
            color: #666;
            text-align: center;
        }
        /* Page break for long catalogs */
        .page-break { page-break-after: always; }
    </style>
</head>
<body>
    <?php echo $pdf_bg_html; // phpcs:ignore -- از قبل در PDF_Template_Manager با esc_url ساخته شده ?>

    <div class="catalog">
        <?php if ( empty( $products_for_template ) ) : ?>
            <p><?php echo esc_html__( 'No products available', 'wc-pdf-catalog' ); ?></p>
        <?php else : ?>
            <?php foreach ( $products_for_template as $p ) : ?>
                <div class="product">
                    <?php if ( ! empty( $p['image'] ) ) : ?>
                        <img src="<?php echo esc_url( $p['image'] ); ?>" alt="<?php echo esc_attr( $p['title'] ); ?>">
                    <?php endif; ?>
                    <div class="meta">
                        <div class="title"><?php echo wp_kses_post( $p['title'] ); ?></div>

                        <?php if ( $show_price === 'yes' && ! empty( $p['price_html'] ) ) : ?>
                            <div class="price"><?php echo wp_kses_post( $p['price_html'] ); ?></div>
                        <?php endif; ?>

                        <?php if ( $show_attributes === 'yes' && ! empty( $p['attributes'] ) ) : ?>
                            <div class="attributes">
                                <?php foreach ( $p['attributes'] as $attr ) : ?>
                                    <div><strong><?php echo esc_html( $attr['name'] ); ?>:</strong> <?php echo esc_html( implode( ', ', $attr['options'] ) ); ?></div>
                                <?php endforeach; ?>
                            </div>
                        <?php endif; ?>
                    </div>
                </div>
            <?php endforeach; ?>
        <?php endif; ?>
    </div>

    <div class="footer-note">
        <?php echo esc_html__( 'Generated by WooCommerce PDF Catalog Generator', 'wc-pdf-catalog' ); ?>
    </div>
</body>
</html>
